Add Eval()
We don't actually traverse the syntax tree yet, which is why the tests
fail: We never encounter an integer node because we never traverse past
the root node in the tree.

Test output:

$go test ./evaluator
--- FAIL: TestEvalIntegerExpressions (0.00s)
    evaluator_test.go:39: object is not Integer.  got=<nil> (<nil>)
    evaluator_test.go:39: object is not Integer.  got=<nil> (<nil>)
FAIL
FAIL    monkey/evaluator        0.011s
FAIL