Fix let statement parsing
Actually parse expressions.  Tests should be passing but they are
failing.  Will need to find cause.

Test results:

$go test ./parser
--- FAIL: TestLetStatements (0.00s)
    parser_test.go:17: parser has 1 errors
    parser_test.go:20: parser error: "no prefix parse function for = found"
FAIL
FAIL    monkey/parser   0.012s
FAIL